import pandas as pd


arquivo = "complicacao.xlsx"

colunas_principais = [
    "COD FILIAL",
    "FILIAL",
    "BASE",
    "SIGLA",
    "ESTADO",
    "SENHA",
    "COMPLICACAO",
    "OBITO",
    "COD USUARIO",
    "USUARIO",
    "TELEFONE",
    "IDADE",
    "IDADE T",
    "EMPRESA",
    "COD PLANO",
    "PLANO",
    "DT ADESAO",
    "TEMPO PLANO",
    "DIAS CARENCIA",
    "TP ATENDIMENTO",
    "TRATAMENTO",
    "PRESTADOR",
    "SOLICITANTE",
    "COD PROCEDIMENTO",
    "PROCEDIMENTO",
    "DT AUTORIZACAO",
    "DT INTERNACAO",
    "DT ENVIO",
    "DIARIAS",
    "UTI",
    "OBSERVACAO",
    "CHAVE",
    "OPERADOR",
    "CONTATO",
    "DT ENVIO MANUAL",
    "DATA DO CONTATO",
    "LIDA",
    "RESPOSTA",
    "STATUS",
    "DATA DE ENVIO",
    "P1",
    "P2",
    "P3",
    "P4",
    "OBSERVA\u00c7\u00d5ES DO CLIENTE",
    "RP1",
    "TENTATIVA",
    "DATA ULTIMA TENTATIVA",
    "TELEFONE TENTADO",
    "ESPECIALISTA",
    "TIPO",
    "UF",
    "DISTRITO",
    "TELEFONE 1",
    "TELEFONE 2",
    "TELEFONE 3",
    "TELEFONE 4",
    "TELEFONE 5",
]

abas = {
    "STATUS": [
        "Conta",
        "HSM",
        "Mensagem",
        "Categoria",
        "Template",
        "Data do envio",
        "Status",
        "Respondido",
        "protocolo",
        "Agendamento",
        "Data agendamento",
        "Status agendamento",
        "Campanha",
        "Agente",
        "Contato",
        "Telefone",
        "ID_Mailing",
        "DT ENVIO",
        "RESPOSTA",
        "NOME_MANIPULADO",
    ],
    "P1": [
        "Data",
        "Nome",
        "Telefone",
        "CPF/CNPJ",
        "Resposta",
        "Op\u00e7\u00e3o",
        "Protocolo",
        "Cod.",
        "N\u00famero xterno",
        "Agente",
        "Canal",
        "Conta",
        "Servi\u00e7o",
        "UF",
        "Classifica\u00e7\u00e3o",
        "Entrada",
        "Classifica\u00e7\u00e3o de IA",
    ],
    "P2": [
        "Data",
        "Nome",
        "Telefone",
        "CPF/CNPJ",
        "Resposta",
        "Op\u00e7\u00e3o",
        "Protocolo",
        "Cod.",
        "N\u00famero xterno",
        "Agente",
        "Canal",
        "Conta",
        "Servi\u00e7o",
        "UF",
        "Classifica\u00e7\u00e3o",
        "Entrada",
        "Classifica\u00e7\u00e3o de IA",
    ],
    "P3": [
        "Data",
        "Nome",
        "Telefone",
        "CPF/CNPJ",
        "Resposta",
        "Op\u00e7\u00e3o",
        "Protocolo",
        "Cod.",
        "N\u00famero xterno",
        "Agente",
        "Canal",
        "Conta",
        "Servi\u00e7o",
        "UF",
        "Classifica\u00e7\u00e3o",
        "Entrada",
        "Classifica\u00e7\u00e3o de IA",
    ],
    "P4": [
        "Data",
        "Nome",
        "Telefone",
        "CPF/CNPJ",
        "Resposta",
        "Op\u00e7\u00e3o",
        "Protocolo",
        "Cod.",
        "N\u00famero xterno",
        "Agente",
        "Canal",
        "Conta",
        "Servi\u00e7o",
        "UF",
        "Classifica\u00e7\u00e3o",
        "Entrada",
        "Classifica\u00e7\u00e3o de IA",
    ],
    "CHAVE ERRO": [
        "CHAVE ERRADA",
        "P1",
        "P2",
        "P3",
        "P4",
        "CHAVE CERTA",
    ],
    "RESUMO": [],
}


df = pd.read_excel(arquivo, sheet_name=0)

for coluna in colunas_principais:
    if coluna not in df.columns:
        df[coluna] = ""

colunas_extras = [coluna for coluna in df.columns if coluna not in colunas_principais]
df = df[colunas_principais + colunas_extras]

with pd.ExcelWriter(arquivo, engine="openpyxl") as writer:
    df.to_excel(writer, sheet_name="BASE", index=False)

    for nome_aba, colunas in abas.items():
        df_aba = pd.DataFrame(columns=colunas)
        df_aba.to_excel(writer, sheet_name=nome_aba, index=False)

print("Planilha organizada com sucesso.")
